### ISSUE TITLE
Gerät zur Datenbank hinzufügen !

### ISSUE THREAD

**Issue by Marfbuilds** [flazer/weather-station#11]
Hey ,Sorry das ich schon wieder nerve 👀
Ich bräuchte mal  Hilfe und zwar beim hinzufügen des Gerätes in der Datenbank.
Leider komme ich da nicht weiter😢 .
Und zwar wüsste ich gerne was ein slug ist und was ich noch alles ändern und eintragen sollte .
Wenn ich richtig bin sollte all dies bei `C:\weather-station-master\web\database\migrations`
eingetragen werden ,oder? 
Danke!
Lg Marvin

**Comment by flazer** [comment]
Hey.
Im Grunde ist der Slug nur ein einmal vorkommendes Wort. Sieh es am besten als alphanumerische unique Id.

Die Migrations werden nur zum Anlegen der Datenbankstruktur genutzt. 
Das Hinzufügen neuer Devices machst du direkt in der Datenbank.
Kannst du hier auch nochmal nachlesen:
https://github.com/flazer/weather-station/tree/master/web

**Comment by Marfbuilds** [comment]
Danke ,
könntest du mir bitte 😕noch erklären wie ich in die Datenbank komme ,oder mir den Dateipfad nennen ?
und was ist mit device id gemeint? 
> Have a look into "device_sensors" and insert your device_id & type_id. >

Ich bin gerade echt verwirrt .
Danke für deine mühe!

**Comment by Marfbuilds** [comment]
Hey.
Anscheinend habt ihr meine frage nicht gelesen .
Könnte mir dennoch jemand antworten oder mir wenigstens  ein Forum empfehlen, da ich nicht immerzu issues nur wegen einer Anfängerfrage eröffnen will.

**Comment by niklask52t** [comment]
Du musst eingeben: DeineIP/phpMyAdmin
