### ISSUE TITLE
Webserver 

### ISSUE THREAD

**Issue by niklask52t** [flazer/weather-station#13]
Ich verstehe nicht genau was ich nun installieren / machen muss damit der Server läuft. Ich habe einen Apache Server mit PHP MySQL und allem drum und dran. Was muss ich nun noch machen?

**Comment by flazer** [comment]
Das ist aber kein Fehler der Software, sondern ein Verständnisproblem deinerseits.
Infos zur Installation findest du in Readme.md: https://github.com/flazer/weather-station/tree/master/web
