### ISSUE TITLE
autoload.php

### ISSUE THREAD

**Issue by niklask52t** [flazer/weather-station#14]
In dem Readme steht man soll "php artisan key:generate" eingeben, doch wenn ich das tue gibt es folgene fehlermeldung: 

PHP Warning:  require(/weather-station/web/vendor/autoload.php): failed to open stream: No such file or directory in /weather-station/web/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/weather-station/web/vendor/autoload.php' (include_path='.:/usr/share/php') in /weather-station/web/artisan on line 18

**Comment by flazer** [comment]
Sieht so aus, als hättest du den ersten Teil der Readme übersprungen:
`run "composer install" & "npm install".`

Also: Composer und NodeJS installieren und nochmal von vorne das Ganze:
https://getcomposer.org/doc/00-intro.md
https://nodejs.org/en/download/
