### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by niklask52t** [flazer/weather-station#17]
Ich glaube ich habe jetzt alles so eingerichtet das es funktinieren sollte. Allerdings sieht die seite letzt so aus als ob da eine CSS datei fehlen würde.
![Unbenannt](https://user-images.githubusercontent.com/50155520/59108013-3ada3c00-893a-11e9-957d-bd62cb099224.PNG)

**Comment by flazer** [comment]
Du musst das CSS via "npm run dev/prod" kompilieren.
Schau dir mal an, wie du NPM installierst und ausführst.
