### ISSUE TITLE
Webserver

### ISSUE THREAD

**Issue by Marfbuilds** [flazer/weather-station#3]
Hey 
Ich hab ein paar Probleme den Webserver zu ereichen.
Ich kommm nicht ganz dahinter ob und was ich in die Zeile 
 
constchar* url = "YOUR_API_URL"
und 
String token = "SECRET_DEVICE_TOKEN";

eintragen muss;
Und wie ich den Webserver erreichen kann denn durch das eintragen der IP in den Browser funktioniert es leider nicht.
Danke für eure Hilfe
Lg

**Comment by Marfbuilds** [comment]
Hey
Irgendwie blicke ich da trzd noch nicht durch sry aber selbst beim einsetzen deiner Default´s 
Und wenn ich dann den Webserver unter der Default Website http://DEINE_DOMAIN.TLD/api/save?
aufrufe funktioniert da wieder nix .
Öffne ich den Webserver überhaupt richtig?
Und wegen des Webservers, also muss ich, wenn ich deinen Webserver benutzen möchte, ihn erst konfigurieren?

**Comment by flazer** [comment]
Natürlich musst du den Webserver erst einmal konfigurieren. Der weiß ja nicht wer er ist und wo welche Projekte liegen. Das "DEINE_DOMAIN.TLD" ist lediglich ein Platzhalter, da musst du deine Domain ebenfalls eintragen. Google am besten mal, wie du einen Nginx oder Apache konfigurierst. 
NPM und Composer musst du auch installieren, um alle nötigen Abhängigkeiten im Projekt zu installieren. 

Grüße.

**Comment by Marfbuilds** [comment]
OK Vielen Dank,
Dann weiß ich ja schon mit was ich mich heute beschäftigen werde.
(hahah)
Lg aus Thüringen

**Comment by Marfbuilds** [comment]
Leider komme ich nicht weiter
Ich hänge am einrichten :/ des Webservers über nginx anscheinend bin ich noch nicht weit genug vorgedrungen in die Thematik.
Wie hast du das alles so hinbekommen ??
Naja und anscheinend muss man bei der Konfiguration im Cmd diese apt-get befehle ausführen 
wobei bei mir immer  
`Der Befehl "apt-get" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.`
als Antwort auftaucht .
Vieleicht hattest du dieses Problem schonmal .
Falls nicht, egal entweder ich fuchs mich da noch rein oder ehhm ja Irgendwann....
Lg
