### ISSUE TITLE
Website zeig nur Unbekannt an

### ISSUE THREAD

**Issue by EinGlasVollKakao** [flazer/weather-station#9]
Hey
Ich habe ein Problem mit der Website.
Bei mir kommen auf dem MySQL-Server Daten an, aber auf der Website steht nur Unbekannt.
![bild](https://user-images.githubusercontent.com/31620323/43994502-54b12ca2-9d9e-11e8-8004-f79d47e24ee2.PNG)

**Comment by flazer** [comment]
Das sieht nach Javascript-Problemen aus. Die Daten werden beim Öffnen der Seite via JS nachgeladen. Hast du ein "npm run dev" bzw. "npm run production" ausgeführt?

**Comment by EinGlasVollKakao** [comment]
Ja, ich habe es ausgeführt, aber ich habe immer noch dasselbe Problem.

**Comment by flazer** [comment]
Es wäre von Vorteil, wenn du nachschaust und hier postest, was beim JS-Call, nachdem die Seite geladen wurde, zurückkommt. Das geht sehr gut mit den DevTools deines Browsers.

**Comment by flazer** [comment]
Jap. Du schickst den Api-Request als GET. Die Route erlaubt nur POST-Requests. 
Hast du am Javascript rumgespielt? Was für ein Browser is'n das?

```
Route::post('/read/', 'ApiController@read')->name('read_values');
```

**Comment by EinGlasVollKakao** [comment]
Ich habe es mit Chrome ausprobiert und ich habe nicht herumgespielt.
Und in Api.php steht `Route::post('/read/', 'ApiController@read')->name('read_values');`

**Comment by kamelohr** [comment]
Ich hatte bis gerade das gleiche Problem. Es lag letztlich am nginx, bei dem sich in der entsprechenden vserver-conf folgende (in dem Fall sinnlose) SEO-Zeile fand:

# SEO trailing slash problem fix
rewrite ^/(.*)/$ /$1 permanent; # remove trailing slash
#rewrite ^(.*[^/])$ $1/ permanent; # add a trailing slash

Auskommentiert, reload, problem fixed.

**Comment by flazer** [comment]
Ah.
Guck an! Wenn dein Webserver da Rewrites macht, dann gehen natürlich die Routen kaputt. 
Hatte ich nicht auf'm Zettel. 
Danke für die Antwort!
Ich mach dann hier mal zu. :)
